#### 1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print("version", np.__version__)
# uncommnet below line for show configuration
# np.show_config()

version 1.24.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
size = null_vector.nbytes
size 

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add) 
#where add is a thing regarding which help you want like np.size etc

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
rev_vector = vector[::-1]
# Other Way
# rev_vector = np.flip(vector)
rev_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
v10 = np.array([1,2,0,0,4,0])
indices = np.nonzero(v10)
indices

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
vIde = np.eye(3)
vIde

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
v12 = np.random.rand(3,3,3)
v12 = np.random.rand(3,3,3)*9 + 1 #for values 1 to 10
v12 = np.random.randint(1,11,size=(3,3,3))
v12

array([[[ 2,  2,  2],
        [ 2,  7,  4],
        [ 7,  1,  1]],

       [[ 6, 10,  9],
        [ 6,  2,  9],
        [10,  9,  5]],

       [[ 4, 10,  2],
        [ 8,  9,  9],
        [ 4,  2,  9]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
v13 = np.random.randint(1,101,size=(10,10))
minVal = np.min(v13)
maxVal = np.max(v13)
print(v13)
print(minVal)
print(maxVal)

[[49 75 13 88 69 46 17 91 33 29]
 [63 57  5 31 94  3 80 96 90 70]
 [17 16 30 60 53 89  3 63 36 46]
 [52 35 27 52 61 60 83 12 81 68]
 [84 75 84 49 42 36 16  7 23 85]
 [14 58 95 59 22 37 74  4 43 64]
 [ 8 25 47 77 10 22 71 20 51 15]
 [65  6 81 90 61 63  6 95 84 25]
 [13 34 91 48 49 70 71 49 50 35]
 [77 21 20 48 19  9 80 15 97 57]]
3
97


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
v14 = np.random.randint(1,101, size=(30))
meanVal = np.mean(v14)
meanVal

42.766666666666666

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
rows = 5
cols = 5

v15 = np.ones((rows,cols))
v15[1:-1, 1:-1] = 0

v15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
v16 = np.pad(v15, pad_width=1, mode='constant', constant_values=0)
v16

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
diagonal_values = [1,2,3,4]
matrix18 = np.diag(diagonal_values, k=-1)
matrix18

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
matrix19 = np.zeros((8,8), dtype=int)
matrix19[1::2, ::2] = 1
matrix19[::2, 1::2] = 1
matrix19

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
shape = (6,7,8)
index = 100

cube20 = np.arange(np.prod(shape)).reshape(shape)
indices = np.unravel_index(index,shape)
indices

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
row_pattern = np.array([[0,1],[1,0]])
chess_board = np.tile(row_pattern, (4,4))
chess_board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
matrix22 = np.random.randint(1,101, size=(5,5))
mean = np.mean(matrix22)
std = np.std(matrix22)

normallized_matrix22 = (matrix22-mean)/std
print(matrix22)
print(normallized_matrix22)

[[25 40 96  6 72]
 [63 36 71  4 20]
 [78 55 75 26 58]
 [59  4 25 26 24]
 [17 44 42 71 36]]
[[-0.71273272 -0.11613725  2.1111525  -1.46842032  1.15659975]
 [ 0.79864247 -0.27522938  1.11682672 -1.54796638 -0.91159788]
 [ 1.39523794  0.48045822  1.27591884 -0.67295969  0.59977731]
 [ 0.63955034 -1.54796638 -0.71273272 -0.67295969 -0.75250575]
 [-1.03091697  0.04295487 -0.03659119  1.11682672 -0.27522938]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
colors = np.array([(255,0,0,255), (0,255,0,255), (0,0,255,255)], dtype=color_dtype)
colors

array([(255,   0,   0, 255), (  0, 255,   0, 255), (  0,   0, 255, 255)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
A = np.random.random((5,3))
B = np.random.random((3,2))
result = np.dot(A,B)
result

array([[1.21572032, 0.75920785],
       [0.34617011, 0.45988323],
       [1.38461343, 0.57824673],
       [1.08924974, 0.56483267],
       [1.33679511, 0.73505684]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[(arr>3)&(arr<8)] *= -1
arr

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1)) #output will be 9
from numpy import *
print(sum(range(5),-1)) #output will be 10
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z #computes exp of each element in vector z with it self.
2 << Z >> 2 # perdorm betwise left and right sift with value 2
Z <- Z # compare each elements of z with its negation using <
1j*Z # muliply each elements of z with 1j imaginary unit
Z/1/1 # divides each elements by 1 then again divides by 1
Z<Z>Z # not legal
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [27]:
arr = np.array([-1.5, -1.2, 0.5, 1.2, 1.5])
rounded_arr = np.ceil(arr)
rounded_arr

array([-1., -1.,  1.,  2.,  2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [28]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(arr1, arr2)
common_values

array([4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [29]:
import warnings
warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [30]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
today = np.datetime64("today")
yesterday = today - np.timedelta64(1, 'D')
tommorrow = today + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tommorrow)

2023-06-03
2023-06-04
2023-06-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

dates = np.arange(start_date, end_date, np.timedelta64(1,'D'))
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [33]:
A = np.array([1,2,4,5])
B = np.array([2,4,5,2])
A += B
A *= (-A/2).astype(np.int32)

print(A)

[ -3 -18 -36 -21]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [34]:
random_array = np.random.rand(5)*10
print(random_array)

[6.9879776  0.89690015 4.36810441 0.44047907 8.20960424]


In [36]:
int_arr1 = random_array.astype(int)
print(int_arr1)

[6 0 4 0 8]


In [37]:
int_arr2 = np.floor(random_array)
print(int_arr2)

[6. 0. 4. 0. 8.]


In [38]:
int_arr3 = np.trunc(random_array)
print(int_arr3)

[6. 0. 4. 0. 8.]


In [39]:
int_arr4 = np.array(list(map(int, random_array)))
print(int_arr4)

[6 0 4 0 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [46]:
row_values = np.arange(5)
matrix = np.empty((5,5), dtype=int)
for i in range(5):
    np.random.shuffle(row_values)
    matrix[i] = row_values
print(matrix)

[[2 3 1 0 4]
 [3 2 0 1 4]
 [0 1 4 3 2]
 [1 4 3 2 0]
 [3 4 2 1 0]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [56]:
def generate_integers():
    for _ in range(10):
        yield np.random.randint(0,100)
array = np.empty(10,dtype=int)
array[i] = next(generate_integers())
print(array)

[70 36 20 50 79 31 57 71 46 52]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [61]:
# vector = np.linspace(0.001, 0.999, 10)
vector = np.arange(0.1, 1, 0.1)
print(vector)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [65]:
vector = np.random.randint(1, 101, size=(10))
print(vector)
print(np.sort(vector))

[10 28 91 64 92  6 17 24  4 20]
[ 4  6 10 17 20 24 28 64 91 92]


#### 41. How to sum a small array faster than np.sum? (★★☆)

Use built int "sum"(sum(arr)) funcion of python

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [67]:
A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.array_equal(A, B)
are_equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [68]:
arr = np.array([1,2,3,4,5])
arr.flags.writeable = False
# raise ValueError
arr[2] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [75]:
cartesian_coords = np.random.randint(0, 11, size = (10,2))

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.hypot(x,y)
theta = np.arctan2(y,x)

polar_coords=np.column_stack((r,theta))

print(cartesian_coords)
print(polar_coords)

[[ 2 10]
 [ 9  8]
 [ 5  1]
 [ 2  5]
 [ 3  6]
 [ 8  8]
 [ 9  4]
 [ 8  2]
 [ 6  4]
 [ 7  1]]
[[10.19803903  1.37340077]
 [12.04159458  0.72664234]
 [ 5.09901951  0.19739556]
 [ 5.38516481  1.19028995]
 [ 6.70820393  1.10714872]
 [11.3137085   0.78539816]
 [ 9.8488578   0.41822433]
 [ 8.24621125  0.24497866]
 [ 7.21110255  0.5880026 ]
 [ 7.07106781  0.14189705]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [74]:
vector = np.random.randint(1,101, size=(10))
print(vector)
max_index = np.argmax(vector)
vector[max_index] = 0
print(vector)

[56 28 97 11 72 87 45 53 76 19]
[56 28  0 11 72 87 45 53 76 19]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)