#### 1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print("version", np.__version__)
# uncommnet below line for show configuration
# np.show_config()

version 1.24.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
size = null_vector.nbytes
size 

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add) 
#where add is a thing regarding which help you want like np.size etc

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
rev_vector = vector[::-1]
# Other Way
# rev_vector = np.flip(vector)
rev_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
v10 = np.array([1,2,0,0,4,0])
indices = np.nonzero(v10)
indices

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
vIde = np.eye(3)
vIde

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
v12 = np.random.rand(3,3,3)
v12 = np.random.rand(3,3,3)*9 + 1 #for values 1 to 10
v12 = np.random.randint(1,11,size=(3,3,3))
v12

array([[[10,  2,  6],
        [ 3,  9,  4],
        [ 8,  1,  2]],

       [[10,  1,  7],
        [ 1,  7,  8],
        [ 5,  4,  6]],

       [[ 2, 10,  9],
        [ 6,  9,  7],
        [ 3,  5,  1]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
v13 = np.random.randint(1,101,size=(10,10))
minVal = np.min(v13)
maxVal = np.max(v13)
print(v13)
print(minVal)
print(maxVal)

[[18 41 14 14 59 13 93 32 10 48]
 [29 77 73 64 94 97 14 62 68 35]
 [52 16 27 71 70 76 13 25 65  7]
 [ 2 15 98 75 67 69  1 57 81 39]
 [49 57 12 96 12 66 89 77 56 46]
 [ 5 70 44 86 86 31 31 59  7 35]
 [84 18 92 84 67 50 46 35 98 63]
 [19 19 97  4 78 87 39 52 42 54]
 [47 36 10  9 47 18 87 13 11 98]
 [47 89 83 89 36 18 64 42 66 40]]
1
98


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
v14 = np.random.randint(1,101, size=(30))
meanVal = np.mean(v14)
meanVal

50.46666666666667

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
rows = 5
cols = 5

v15 = np.ones((rows,cols))
v15[1:-1, 1:-1] = 0

v15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
v16 = np.pad(v15, pad_width=1, mode='constant', constant_values=0)
v16

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
diagonal_values = [1,2,3,4]
matrix18 = np.diag(diagonal_values, k=-1)
matrix18

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
matrix19 = np.zeros((8,8), dtype=int)
matrix19[1::2, ::2] = 1
matrix19[::2, 1::2] = 1
matrix19

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
shape = (6,7,8)
index = 100

cube20 = np.arange(np.prod(shape)).reshape(shape)
indices = np.unravel_index(index,shape)
indices

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
row_pattern = np.array([[0,1],[1,0]])
chess_board = np.tile(row_pattern, (4,4))
chess_board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
matrix22 = np.random.randint(1,101, size=(5,5))
mean = np.mean(matrix22)
std = np.std(matrix22)

normallized_matrix22 = (matrix22-mean)/std
print(matrix22)
print(normallized_matrix22)

[[ 73  88  35  72  94]
 [ 90  25  18  60  28]
 [ 90  71 100  18  73]
 [ 13  39  88  90  40]
 [ 79  80  65  81  65]]
[[ 0.37158549  0.92896372 -1.04043937  0.33442694  1.15191502]
 [ 1.00328082 -1.41202486 -1.6721347  -0.11147565 -1.30054921]
 [ 1.00328082  0.29726839  1.37486631 -1.6721347   0.37158549]
 [-1.85792745 -0.89180517  0.92896372  1.00328082 -0.85464663]
 [ 0.59453678  0.63169533  0.0743171   0.66885388  0.0743171 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
colors = np.array([(255,0,0,255), (0,255,0,255), (0,0,255,255)], dtype=color_dtype)
colors

array([(255,   0,   0, 255), (  0, 255,   0, 255), (  0,   0, 255, 255)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
A = np.random.random((5,3))
B = np.random.random((3,2))
result = np.dot(A,B)
result

array([[0.86169863, 0.97725523],
       [1.2294323 , 1.26413682],
       [0.82384457, 0.77073499],
       [0.69166901, 0.76155436],
       [0.8894899 , 0.88219792]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[(arr>3)&(arr<8)] *= -1
arr

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1)) #output will be 9
from numpy import *
print(sum(range(5),-1)) #output will be 10
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z #computes exp of each element in vector z with it self.
2 << Z >> 2 # perdorm betwise left and right sift with value 2
Z <- Z # compare each elements of z with its negation using <
1j*Z # muliply each elements of z with 1j imaginary unit
Z/1/1 # divides each elements by 1 then again divides by 1
Z<Z>Z # not legal
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [27]:
arr = np.array([-1.5, -1.2, 0.5, 1.2, 1.5])
rounded_arr = np.ceil(arr)
rounded_arr

array([-1., -1.,  1.,  2.,  2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [28]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(arr1, arr2)
common_values

array([4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [29]:
import warnings
warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [30]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
today = np.datetime64("today")
yesterday = today - np.timedelta64(1, 'D')
tommorrow = today + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tommorrow)

2023-06-05
2023-06-06
2023-06-07


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

dates = np.arange(start_date, end_date, np.timedelta64(1,'D'))
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [33]:
A = np.array([1,2,4,5])
B = np.array([2,4,5,2])
A += B
A *= (-A/2).astype(np.int32)

print(A)

[ -3 -18 -36 -21]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [34]:
random_array = np.random.rand(5)*10
print(random_array)

[0.03583184 7.40322812 9.56859617 8.31656775 6.6293465 ]


In [35]:
int_arr1 = random_array.astype(int)
print(int_arr1)

[0 7 9 8 6]


In [36]:
int_arr2 = np.floor(random_array)
print(int_arr2)

[0. 7. 9. 8. 6.]


In [37]:
int_arr3 = np.trunc(random_array)
print(int_arr3)

[0. 7. 9. 8. 6.]


In [38]:
int_arr4 = np.array(list(map(int, random_array)))
print(int_arr4)

[0 7 9 8 6]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
row_values = np.arange(5)
matrix = np.empty((5,5), dtype=int)
for i in range(5):
    np.random.shuffle(row_values)
    matrix[i] = row_values
print(matrix)

[[2 3 4 0 1]
 [1 0 3 2 4]
 [4 3 0 2 1]
 [4 0 2 3 1]
 [3 1 0 4 2]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def generate_integers():
    for _ in range(10):
        yield np.random.randint(0,100)
array = np.empty(10,dtype=int)
array[i] = next(generate_integers())
print(array)

[         0          0          0 1075576832         39 1075970048
          0 1075838976          0 1075314688]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
# vector = np.linspace(0.001, 0.999, 10)
vector = np.arange(0.1, 1, 0.1)
print(vector)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
vector = np.random.randint(1, 101, size=(10))
print(vector)
print(np.sort(vector))

[80 23 13 76 38 29 61 48 21 47]
[13 21 23 29 38 47 48 61 76 80]


#### 41. How to sum a small array faster than np.sum? (★★☆)

Use built int "sum"(sum(arr)) funcion of python

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.array_equal(A, B)
are_equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
arr = np.array([1,2,3,4,5])
arr.flags.writeable = False
# raise ValueError
# arr[2] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
cartesian_coords = np.random.randint(0, 11, size = (10,2))

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.hypot(x,y)
theta = np.arctan2(y,x)

polar_coords=np.column_stack((r,theta))

print(cartesian_coords)
print(polar_coords)

[[5 5]
 [6 9]
 [0 2]
 [7 4]
 [9 0]
 [3 2]
 [5 1]
 [2 4]
 [3 9]
 [0 1]]
[[ 7.07106781  0.78539816]
 [10.81665383  0.98279372]
 [ 2.          1.57079633]
 [ 8.06225775  0.51914611]
 [ 9.          0.        ]
 [ 3.60555128  0.5880026 ]
 [ 5.09901951  0.19739556]
 [ 4.47213595  1.10714872]
 [ 9.48683298  1.24904577]
 [ 1.          1.57079633]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
vector = np.random.randint(1,101, size=(10))
print(vector)
max_index = np.argmax(vector)
vector[max_index] = 0
print(vector)

[45 64 37 76 14 20 62  4 20 40]
[45 64 37  0 14 20 62  4 20 40]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
n_points = 10
x = np.linspace(0,1,n_points)
y = np.linspace(0,1,n_points)

X, Y = np.meshgrid(x,y)
coordinates = np.column_stack((X.flatten(), Y.flatten()))
print(coordinates)

[[0.         0.        ]
 [0.11111111 0.        ]
 [0.22222222 0.        ]
 [0.33333333 0.        ]
 [0.44444444 0.        ]
 [0.55555556 0.        ]
 [0.66666667 0.        ]
 [0.77777778 0.        ]
 [0.88888889 0.        ]
 [1.         0.        ]
 [0.         0.11111111]
 [0.11111111 0.11111111]
 [0.22222222 0.11111111]
 [0.33333333 0.11111111]
 [0.44444444 0.11111111]
 [0.55555556 0.11111111]
 [0.66666667 0.11111111]
 [0.77777778 0.11111111]
 [0.88888889 0.11111111]
 [1.         0.11111111]
 [0.         0.22222222]
 [0.11111111 0.22222222]
 [0.22222222 0.22222222]
 [0.33333333 0.22222222]
 [0.44444444 0.22222222]
 [0.55555556 0.22222222]
 [0.66666667 0.22222222]
 [0.77777778 0.22222222]
 [0.88888889 0.22222222]
 [1.         0.22222222]
 [0.         0.33333333]
 [0.11111111 0.33333333]
 [0.22222222 0.33333333]
 [0.33333333 0.33333333]
 [0.44444444 0.33333333]
 [0.55555556 0.33333333]
 [0.66666667 0.33333333]
 [0.77777778 0.33333333]
 [0.88888889 0.33333333]
 [1.         0.33333333]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [48]:
X = np.array([1,2,3,4,5])
Y = np.array([2,4,6,8,10])

cauchy_matrix = 1 / (np.subtract.outer(X,Y))
print(cauchy_matrix)

[[-1.         -0.33333333 -0.2        -0.14285714 -0.11111111]
 [        inf -0.5        -0.25       -0.16666667 -0.125     ]
 [ 1.         -1.         -0.33333333 -0.2        -0.14285714]
 [ 0.5                inf -0.5        -0.25       -0.16666667]
 [ 0.33333333  1.         -1.         -0.33333333 -0.2       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [49]:
# List of NumPy scalar types
scalar_types = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16,
                np.uint32, np.uint64, np.float16, np.float32, np.float64, np.complex64,
                np.complex128]

for type in scalar_types:
    min_value = np.iinfo(type).min if np.issubdtype(type, np.integer) else np.finfo(type).min
    max_value = np.iinfo(type).max if np.issubdtype(type, np.integer) else np.finfo(type).max
    print(f"{type.__name__}: {min_value} to {max_value}")

int8: -128 to 127
int16: -32768 to 32767
int32: -2147483648 to 2147483647
int64: -9223372036854775808 to 9223372036854775807
uint8: 0 to 255
uint16: 0 to 65535
uint32: 0 to 4294967295
uint64: 0 to 18446744073709551615
float16: -65504.0 to 65504.0
float32: -3.4028234663852886e+38 to 3.4028234663852886e+38
float64: -1.7976931348623157e+308 to 1.7976931348623157e+308
complex64: -3.4028234663852886e+38 to 3.4028234663852886e+38
complex128: -1.7976931348623157e+308 to 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★☆☆)

In [50]:
print(arr);

[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [51]:
vector = np.array([1,2,5,7,9])
scalar = 8
abs_diff = np.abs(vector-scalar)
closest_ind = np.argmin(abs_diff)
closest = vector[closest_ind]
print(closest)


7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [52]:
new_dtype = np.dtype([('position', [('x', float), ('y', float)]), 
                      ('color', [('r', int), ('g', int), ('b', int)])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
random_vector = np.random.randint(1, 11, size=(100, 2))
distances = np.linalg.norm(random_vector, axis=1)
print(distances)

[10.         10.19803903  3.16227766 11.18033989  7.21110255  8.06225775
  6.08276253  1.41421356  7.61577311  7.28010989  8.06225775  5.38516481
 10.63014581  3.16227766  9.8488578  11.40175425  6.70820393  8.94427191
  5.09901951  9.89949494  7.61577311 12.04159458 10.44030651 10.29563014
  9.48683298  9.21954446  7.81024968  6.40312424  6.70820393  7.07106781
  5.09901951 10.81665383  8.24621125 10.19803903  6.08276253  3.60555128
 10.04987562  5.38516481 10.63014581  7.07106781 10.44030651  4.24264069
  3.16227766  4.47213595 10.77032961 10.77032961  4.12310563  9.48683298
  3.60555128 11.18033989 10.44030651  7.28010989  5.          8.06225775
 10.29563014  5.          8.06225775 11.66190379 10.19803903  7.61577311
  4.12310563 10.77032961  8.06225775 10.19803903  9.43398113  4.47213595
  4.24264069  3.60555128 11.40175425  3.16227766 10.29563014 12.72792206
 11.18033989 10.81665383 11.3137085   9.21954446  3.16227766  9.21954446
  9.05538514  8.06225775  4.24264069  6.70820393  8

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
float_arr = np.array([1.5,2.7,3.2], dtype = np.float32)
float_arr = float_arr.astype(np.int32)
print(float_arr)

[1 2 3]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
def gaussian_array(shape, center, sigma):
    x, y = np.meshgrid(range(shape[0]), range(shape[1]))
    x_center, y_center = center
    exponent = -((x - x_center) ** 2 + (y - y_center) ** 2) / (2 * sigma ** 2)
    array = np.exp(exponent)
    return array

shape = (10,10)
center = (5,5)
sigma = 2

gaussian = gaussian_array(shape, center, sigma)
print(gaussian)

[[0.00193045 0.00594622 0.01426423 0.0266491  0.03877421 0.04393693
  0.03877421 0.0266491  0.01426423 0.00594622]
 [0.00594622 0.01831564 0.04393693 0.082085   0.11943297 0.13533528
  0.11943297 0.082085   0.04393693 0.01831564]
 [0.01426423 0.04393693 0.10539922 0.19691168 0.2865048  0.32465247
  0.2865048  0.19691168 0.10539922 0.04393693]
 [0.0266491  0.082085   0.19691168 0.36787944 0.53526143 0.60653066
  0.53526143 0.36787944 0.19691168 0.082085  ]
 [0.03877421 0.11943297 0.2865048  0.53526143 0.77880078 0.8824969
  0.77880078 0.53526143 0.2865048  0.11943297]
 [0.04393693 0.13533528 0.32465247 0.60653066 0.8824969  1.
  0.8824969  0.60653066 0.32465247 0.13533528]
 [0.03877421 0.11943297 0.2865048  0.53526143 0.77880078 0.8824969
  0.77880078 0.53526143 0.2865048  0.11943297]
 [0.0266491  0.082085   0.19691168 0.36787944 0.53526143 0.60653066
  0.53526143 0.36787944 0.19691168 0.082085  ]
 [0.01426423 0.04393693 0.10539922 0.19691168 0.2865048  0.32465247
  0.2865048  0.1969116

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [61]:
def place_elements(arr, p, value):
    shape = arr.shape
    indices = np.random.choice(range(shape[0] * shape[1]), p, replace=False)
    indices = np.unravel_index(indices, shape)
    arr[indices] = value
    return arr

shape = (8,8)
p = 10
value = 1
starting_arr = np.zeros(shape)
our_new_array = place_elements(starting_arr, p, value)
print(our_new_array)

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [72]:
def subtract_row_mean(matrix):
    row_means = np.mean(matrix, axis=1, keepdims=True)
    print(f"Every rows mean:\n {row_means}")
    matrix = matrix - row_means
    return matrix

matrix = np.random.randint(1,11,size=(3,4))
print(f"Original matrix:\n {matrix}")
result = subtract_row_mean(matrix)
print(f"Formated matrix:\n {result}")

Original matrix:
 [[ 2  3 10  2]
 [ 4  3  5  7]
 [ 8  1  6  5]]
Every rows mean:
 [[4.25]
 [4.75]
 [5.  ]]
Formated matrix:
 [[-2.25 -1.25  5.75 -2.25]
 [-0.75 -1.75  0.25  2.25]
 [ 3.   -4.    1.    0.  ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [68]:
def sort_by_nth_col(arr,n):
    column_to_sort = arr[:,n]
    sorted_indices = np.argsort(column_to_sort)
    sorted_arr = arr[sorted_indices]
    return sorted_arr

arr = np.array([[1,2,3,4],
                [4,2,6,2],
                [3,5,1,6]])

sorted_arr = sort_by_nth_col(arr, 2)
print(sorted_arr)

[[3 5 1 6]
 [1 2 3 4]
 [4 2 6 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [73]:
def has_null_column(arr):
    null_col = np.all(arr == 0, axis = 0)
    return np.any(null_col)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [75]:
def nearest_value(arr, val):
    # find the min diff between all the values of array and the value
    index = np.abs(arr-val).argmin()
    nearest_val = arr[index]
    return nearest_val

arr = np.array([1,4,2,6,9,7])
target = 3

nearest = nearest_value(arr, target)
print(nearest)


4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [79]:
def compute_sum_with_iterator(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i, row in enumerate(A):
        for j, col in enumerate(B.T):
            result[i,j] = np.sum(row*col)
    return  result

array1 = np.array([[1],
                   [3],
                   [2]])
array2 = np.array([[5, 6, 8]])

result = compute_sum_with_iterator(array1, array2)
print(result)


[[ 5.  6.  8.]
 [15. 18. 24.]
 [10. 12. 16.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [80]:
class NamedArry:
    def __init__(self, name, arr):
        self.name = name
        self.arr = arr

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)